# Generated by Django 5.2 on 2025-08-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_heroslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslider',
            name='button_link',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='button_text',
            field=models.CharField(default='Shop Now', max_length=50),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
