# Generated by Django 5.1.1 on 2025-08-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_heroslider_is_active_alter_heroslider_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(default='30 Years Of Experience', max_length=100)),
                ('title', models.CharField(default='ABOUT US', max_length=200)),
                ('subtitle', models.CharField(default='World Largest Online Shopping Marketplace For You.', max_length=300)),
                ('content', models.TextField(default='')),
                ('button_text', models.CharField(default='Discover More →', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.DeleteModel(
            name='HeroSlider',
        ),
    ]
