# Generated by Django 5.1.1 on 2025-08-24 17:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_aboutpage_delete_heroslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('highlighted_text', models.CharField(blank=True, max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('button_text', models.CharField(default='Discover More', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Contents',
            },
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
    ]
