# Generated by Django 5.1.1 on 2025-08-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_aboutpagecontent_delete_aboutpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('order', '-created_at'), 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AddField(
            model_name='author',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
    ]
