# Generated by Django 5.1.1 on 2025-08-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('button_text', models.CharField(default='Shop Now', max_length=50, verbose_name='Текст кнопки')),
                ('button_link', models.CharField(default='#', max_length=200, verbose_name='Ссылка кнопки')),
                ('image', models.ImageField(help_text='Рекомендуемый размер: 600x600px', upload_to='slider/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('subtitle_delay', models.DecimalField(decimal_places=1, default=0.25, max_digits=3, verbose_name='Задержка подзаголовка (сек)')),
                ('title_delay', models.DecimalField(decimal_places=1, default=0.5, max_digits=3, verbose_name='Задержка заголовка (сек)')),
                ('text_delay', models.DecimalField(decimal_places=1, default=0.75, max_digits=3, verbose_name='Задержка текста (сек)')),
                ('button_delay', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, verbose_name='Задержка кнопки (сек)')),
                ('image_delay', models.DecimalField(decimal_places=1, default=0.25, max_digits=3, verbose_name='Задержка изображения (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Слайд героя',
                'verbose_name_plural': 'Слайды героя',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
