# Generated by Django 5.1.1 on 2025-08-24 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_heroslider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslider',
            name='button_delay',
        ),
        migrations.RemoveField(
            model_name='heroslider',
            name='image_delay',
        ),
        migrations.RemoveField(
            model_name='heroslider',
            name='subtitle_delay',
        ),
        migrations.RemoveField(
            model_name='heroslider',
            name='text_delay',
        ),
        migrations.RemoveField(
            model_name='heroslider',
            name='title_delay',
        ),
    ]
