# Generated by Django 5.1.1 on 2025-08-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_heroslider_button_delay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslider',
            name='title',
        ),
        migrations.AddField(
            model_name='heroslider',
            name='title_line1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Первая строка заголовка'),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='title_line2',
            field=models.CharField(default='Goemart', max_length=100, verbose_name='Вторая строка заголовка (цветная часть)'),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='title_line3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Третья строка заголовка'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='subtitle',
            field=models.CharField(max_length=200, verbose_name='Подзаголовок (верхняя зеленая строка)'),
        ),
    ]
