# Generated by Django 5.1.1 on 2025-08-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='name',
        ),
    ]
