# Generated by Django 5.1.1 on 2025-08-24 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_remove_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslider',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Продукт, на который будет вести кнопка Shop Now', null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Связанный продукт'),
        ),
    ]
