# Generated by Django 5.1.1 on 2025-08-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_heroslider_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
