# Generated by Django 5.1.1 on 2025-08-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_remove_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslider',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
